name = input("Naam: ")
adres = input("Adres: ")
postcode = input("Postcode: ")
woonplaats = input("Woonplaats: ")
print("-------------------------------------")
print("|  Your name is: " + name)
print("|  Your adress is: "+ adres)
print("|  Your postcode is: "+ postcode)
print("|  You live at: "+ woonplaats)
print("-------------------------------------")